作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意<br>
題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。

In [2]:
import numpy as np

In [7]:
arithmetic_sequence = np.linspace(0, 20, 21)
print("首數為0，尾數為20，公差為1的數列：")
print(arithmetic_sequence)

首數為0，尾數為20，公差為1的數列：
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


In [8]:
even_seq = []
for i in arithmetic_sequence:
  if i % 2 == 0:
    even_seq.append(i)
print("以上數列的偶數數列")
print(even_seq)

以上數列的偶數數列
[0.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0]


In [9]:
mul_three_seq = []
for i in arithmetic_sequence:
  if i % 3 == 0:
    mul_three_seq.append(i)
print("以上數列中3的倍數數列")
print(mul_three_seq)

以上數列中3的倍數數列
[0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0]


課程解答：

In [8]:
a = np.arange(0, 20)
print(a)
print(a[::2])
print(a[::3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]
